### ISSUE TITLE
Audit existing components

### ISSUE THREAD

**Issue by jacobscarfmerrell** [jacobscarfmerrell/myword#3]
Open Questions:
- what components do we not yet have and need?
- what components, if any, can we get rid of/clean up?
- how do we want to organize those components (/pages, /components?)

TODO:
- [ ] answer these questions in comments on the issue

**Comment by ngalter** [comment]
My initial review shows a general structure for a multi (2) user game using websocket technology.  I laid out the existing components here https://docs.google.com/spreadsheets/d/1F7vTDLQpeC7OyIgTo6_KwOw2mow62QS4al22xm62SEQ/edit?usp=sharing.  

here are some ideas for user input functions that I think are required 
https://docs.google.com/spreadsheets/d/1F7vTDLQpeC7OyIgTo6_KwOw2mow62QS4al22xm62SEQ/edit?usp=sharing

regarding organizing components.  I think that is a joint discussion.  I know in class there was a preference for multiple index.js files, one for each directory.  I understand this approach,  but it can be very confusing.  I know Brittany has a certain way she liked to create her directories when she developed her code.  I think we all should settle on something together and then follow it.  I don't think I have the experience to make a final decision.
